

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  host: localhost
  username: root
  password: 870412

development:
  <<: *default
  database: forum_db

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>


# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3


# test:
#   <<: *default
#   database: storage/test.sqlite3


# production:
#   primary:
#     <<: *default
#     database: storage/production.sqlite3
#   cache:
#     <<: *default
#     database: storage/production_cache.sqlite3
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: storage/production_queue.sqlite3
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: storage/production_cable.sqlite3
#     migrations_paths: db/cable_migrate
